title: SunSaar
description: A clean blog about Solar Energy and Sustainability
url: https://sunsaar.in  # Replace with your domain
baseurl: ""  # Leave empty for root

remote_theme: no-style-please
theme_mode: dark