title: My Minimal Blog
description: A clean blog built with Jekyll and GitHub Actions
url: https://sunsaar.in  # Replace with your domain
baseurl: ""  # Leave empty for root

theme: jekyll-theme-minimal
