title: SunSaar
tagline: Something upcoming
description: >-
  A personal blog powered by Jekyll and Chirpy
url: "https://sunsaar.in"
baseurl: ""
theme: jekyll-dash
# theme_mode: dark


# Sidebar navigation (for docs-style layout)
sidebar:
  nav:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"

# Tab bar configuration matching the docs website look
tab_bar:
  - title: "Overview"
    url: "/docs/overview/"
  - title: "Getting Started"
    url: "/docs/getting-started/"
