title: SunSaar
description: A clean blog about Solar Energy and Sustainability
url: https://sunsaar.in  # Replace with your domain
baseurl: ""  # Leave empty for root

remote_theme: riggraz/no-style-please
theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  date_format: "%d-%m-%Y"

sass:
  load_paths:
    - assets/css

plugins: [jekyll-feed, jekyll-seo-tag, jekyll-remote-theme]